---
AWSTemplateFormatVersion: "2010-09-09"
Description: Magic Beans bootstrap template to create a devops repository and bucket
Parameters:
  repositoryName:
    Type: String
    Description: The name of the Devops CloudFormation Repository
  repositoryDescription:
    Type: String
    Description: The description of the Devops CloudFormation Repository
  devopsBucketName:
    Type: String
    Description: Name of the S3 Bucket used to store DevOps artifacts
  devopsUserName:
    Type: String
    Description: Name of the DevOps user
  devopsGroupName:
    Type: String
    Description: Name of the DevOps group
Resources:
  DevopsRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref repositoryName
      RepositoryDescription: !Ref repositoryDescription
  DevopsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref devopsBucketName
      VersioningConfiguration:
        Status: Enabled
  DevopsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref devopsGroupName
  DevopsUser:
    Type: AWS::IAM::User
    DependsOn: DevopsGroup
    Properties:
      Groups:
        - !Ref devopsGroupName
      UserName: !Ref devopsUserName
  DevopsPolicy:
    Type: AWS::IAM::ManagedPolicy
    DependsOn: DevopsGroup
    Properties:
      Description: Managed policy for DevOps group
      Groups:
        - !Ref devopsGroupName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action:
              -
                "*"
            Resource:
              -
                "*"
  DevopsAccessKey:
    Type: AWS::IAM::AccessKey
    DependsOn: DevopsUser
    Properties:
      UserName: !Ref devopsUserName
Outputs:
  UserId:
    Description: ID of the Devops User
    Value: !Ref DevopsUser
  UserAccessKeyId:
    Description: Access Key ID of the Devops User
    Value: !Ref DevopsAccessKey
  UserSecretAccessKey:
    Description: Secret Access Key of the Devops User
    Value: !GetAtt DevopsAccessKey.SecretAccessKey
  RepositoryCloneUrl:
    Description: Repository Clone Url
    Value: !GetAtt DevopsRepository.CloneUrlSsh
  S3BucketUrl:
    Description: Devops Artifact Bucket Url
    Value: !GetAtt DevopsS3Bucket.WebsiteURL